function roundComplete(c){return Array.from({length:18},(_,h)=>holeReady(c,h)).every(Boolean)}
function grossBirdie(c,p){if(c==='kingsbarns')return false;return state.scores[c][p].some((g,h)=>g!=null&&g===holePar(c,p,h)-1)}
function seedResults(){const c='kingsbarns';let rows=PLAYER_ORDER.map(p=>({p,pts:sumHoles(h=>stableford(c,p,h)||0,0,18),b9:sumHoles(h=>stableford(c,p,h)||0,9,18),b6:sumHoles(h=>stableford(c,p,h)||0,12,18),b3:sumHoles(h=>stableford(c,p,h)||0,15,18),h18:stableford(c,p,17)||0}));rows.sort((a,b)=>b.pts-a.pts||b.b9-a.b9||b.b6-a.b6||b.b3-a.b3||b.h18-a.h18||PLAYER_ORDER.indexOf(a.p)-PLAYER_ORDER.indexOf(b.p));return rows}
function sumHoles(fn,s,e){let x=0;for(let h=s;h<e;h++)x+=fn(h)||0;return x}
function singlesMatch(c,a,b,subset=[0,18]){const cha=courseHandicap(c,a),chb=courseHandicap(c,b);if(cha==null||chb==null)return null;const low=Math.min(cha,chb);let holesA=0,holesB=0;let holeResults=[];for(let h=subset[0];h<subset[1];h++){const ga=gross(c,a,h),gb=gross(c,b,h);if(ga==null||gb==null){holeResults.push(null);continue}const sa=strokesFromPH(cha-low,holeSI(c,a,h)),sb=strokesFromPH(chb-low,holeSI(c,b,h));const na=ga-sa,nb=gb-sb;if(na<nb)holesA++;else if(nb<na)holesB++;holeResults.push(na<nb?a:nb<na?b:'half')}return{a,b,holesA,holesB,diff:holesA-holesB,holeResults}}
function fullSinglesResult(c,a,b){const full=singlesMatch(c,a,b,[0,18]);if(!full)return null;const played=full.holeResults.filter(x=>x!==null).length,rem=18-played,closed=Math.abs(full.diff)>rem||(played===18&&full.diff!==0);if(closed){return{winner:full.diff>0?a:b,loser:full.diff>0?b:a,display:played===18?`${playerLabel(full.diff>0?a:b)} ${Math.abs(full.diff)} up`:matchStateText(full),full}}if(played===18&&full.diff===0){
  for(const sub of [[9,18],[12,18],[15,18],[17,18]]){const r=singlesMatch(c,a,b,sub);if(r.diff!==0)return{winner:r.diff>0?a:b,loser:r.diff>0?b:a,display:'Countback',full};}
  const coin=state.manual.coin[c+'_'+a+'_'+b];if(coin)return{winner:coin,loser:coin===a?b:a,display:'Coin flip',full};return{winner:null,loser:null,display:'Coin flip needed',full};}
 return{winner:null,loser:null,display:matchStateText(full),full}}
function matchStateText(r){let played=r.holeResults.filter(x=>x!==null).length,lead=Math.abs(r.diff),rem=18-played;if(lead===0)return played?`All square thru ${played}`:'All square';let leader=r.diff>0?r.a:r.b;let name=state.players[leader].name;if(lead>rem)return `${name} wins ${lead}&${rem}`;return `${name} ${lead} up thru ${played}`}
function seedOrder(){return state.locks.seeds||seedResults().map(x=>x.p)}
function semis(){const seeds=seedOrder();return[[seeds[0],seeds[3]],[seeds[1],seeds[2]]]}
function semifinalResults(){return semis().map(m=>fullSinglesResult('northberwick',m[0],m[1]))}
function computedFinalMatches(){const sr=semifinalResults();if(sr.some(x=>!x||!x.winner))return null;return{champ:[sr[0].winner,sr[1].winner],consolation:[sr[0].loser,sr[1].loser]}}
function finalMatches(){return state.locks.finals||computedFinalMatches()}
function fourballTeams(){const s=seedOrder();return[[s[0],s[3]],[s[1],s[2]]]}
function fourballHole(h,teams=fourballTeams()){const scores=teams.map(team=>Math.min(...team.map(p=>{const g=gross('elie',p,h);return g==null?999:g-regularStrokes('elie',p,h)})));if(scores.includes(999))return null;return scores[0]<scores[1]?0:scores[1]<scores[0]?1:'half'}
function fourballResult(sub=[0,18]){let a=0,b=0,played=0;for(let h=sub[0];h<sub[1];h++){let r=fourballHole(h);if(r==null)continue;played++;if(r===0)a++;else if(r===1)b++;}return{a,b,diff:a-b,played}}
function resolveFourball(){let f=fourballResult(),rem=18-f.played,lead=Math.abs(f.diff);if(f.diff&&lead>rem)return{winner:f.diff>0?0:1,display:`Team ${f.diff>0?1:2} wins ${lead}&${rem}`,raw:f};if(f.played===18&&f.diff)return{winner:f.diff>0?0:1,display:`Team ${f.diff>0?1:2} ${lead} up`,raw:f};if(roundComplete('elie')&&f.diff===0){for(const sub of [[9,18],[12,18],[15,18],[17,18]]){let r=fourballResult(sub);if(r.diff)return{winner:r.diff>0?0:1,display:'Countback',raw:f}}const coin=state.manual.coin.elie;if(coin==='team0'||coin==='team1')return{winner:coin==='team0'?0:1,display:'Coin flip',raw:f};return{winner:null,display:'Coin flip needed',raw:f}}if(f.diff)return{winner:null,display:`Team ${f.diff>0?1:2} ${lead} up thru ${f.played}`,raw:f};return{winner:null,display:f.played?`All square thru ${f.played}`:'All square',raw:f}}
function cbumBeforeCastle(){return cbumStandings(['elie','northberwick'])}
function bumsteadTeams(){if(state.locks.bumstead)return state.locks.bumstead;const s=cbumBeforeCastle().map(x=>x.p);return[[s[0],s[3]],[s[1],s[2]]]}
function bumsteadHole(h,teams=bumsteadTeams()){const nets=teams.map(team=>team.map(p=>{const g=gross('castlestuart',p,h);if(g==null)return null;const raw=g-regularStrokes('castlestuart',p,h),cap=holePar('castlestuart',p,h)+2;return Math.min(raw,cap)}));if(nets.flat().some(x=>x==null))return null;let out=[0,0];const low=[Math.min(...nets[0]),Math.min(...nets[1])],high=[Math.max(...nets[0]),Math.max(...nets[1])],total=[nets[0][0]+nets[0][1],nets[1][0]+nets[1][1]];for(const pair of [low,high,total]){if(pair[0]<pair[1])out[0]+=1;else if(pair[1]<pair[0])out[1]+=1;else{out[0]+=.5;out[1]+=.5}}return{points:out,low,high,total,nets}}
function bumsteadResult(sub=[0,18]){let p=[0,0],played=0;for(let h=sub[0];h<sub[1];h++){const r=bumsteadHole(h);if(!r)continue;played++;p[0]+=r.points[0];p[1]+=r.points[1]}return{p,diff:p[0]-p[1],played}}
function resolveBumstead(){let f=bumsteadResult(),remainingPts=(18-f.played)*3;if(f.diff&&Math.abs(f.diff)>remainingPts)return{winner:f.diff>0?0:1,display:`Team ${f.diff>0?1:2} clinches, ${f.p[0]} to ${f.p[1]}`,raw:f};if(roundComplete('castlestuart')){if(f.diff)return{winner:f.diff>0?0:1,display:`Team ${f.diff>0?1:2} wins, ${f.p[0]} to ${f.p[1]}`,raw:f};for(const sub of [[9,18],[12,18],[15,18],[17,18]]){const r=bumsteadResult(sub);if(r.diff)return{winner:r.diff>0?0:1,display:'Countback',raw:f}}return{winner:null,display:'Tied after countback',raw:f}}return{winner:null,display:`${f.p[0]} to ${f.p[1]}${f.played?` thru ${f.played}`:''}`,raw:f}}
function wolfForHole(h){return state.wolfOrder[h%4]}
function wolfPoints(){let totals=Object.fromEntries(PLAYER_ORDER.map(p=>[p,0]));let byHole=[];for(let h=0;h<18;h++){const wolf=wolfForHole(h),call=state.wolfCalls[h],pts=Object.fromEntries(PLAYER_ORDER.map(p=>[p,0]));if(!call||!completedHole('brora',h)){byHole.push(pts);continue}const n=Object.fromEntries(PLAYER_ORDER.map(p=>[p,net('brora',p,h)]));if(call.type==='partner'){
 const partner=call.partner,side=[wolf,partner],opp=PLAYER_ORDER.filter(p=>!side.includes(p)),bestSide=Math.min(...side.map(p=>n[p])),bestOpp=Math.min(...opp.map(p=>n[p]));if(bestSide<bestOpp)side.forEach(p=>pts[p]++);else if(bestOpp<bestSide)opp.forEach(p=>pts[p]++);
 }else{const opp=PLAYER_ORDER.filter(p=>p!==wolf),bestOpp=Math.min(...opp.map(p=>n[p]));if(n[wolf]<bestOpp)pts[wolf]+=call.type==='blind'?4:3;else if(n[wolf]>bestOpp)opp.forEach(p=>pts[p]++);}
 PLAYER_ORDER.forEach(p=>totals[p]+=pts[p]);byHole.push(pts)}return{totals,byHole}}
function wolfRanks(){const wp=wolfPoints();let rows=PLAYER_ORDER.map(p=>({p,pts:wp.totals[p],b9:sumHoles(h=>wp.byHole[h][p],9,18),b6:sumHoles(h=>wp.byHole[h][p],12,18),b3:sumHoles(h=>wp.byHole[h][p],15,18)}));rows.sort((a,b)=>b.pts-a.pts||b.b9-a.b9||b.b6-a.b6||b.b3-a.b3||PLAYER_ORDER.indexOf(a.p)-PLAYER_ORDER.indexOf(b.p));return rows}