function stablefordRows(c){return PLAYER_ORDER.map(p=>({p,pts:sumHoles(h=>stableford(c,p,h)||0,0,18),b9:sumHoles(h=>stableford(c,p,h)||0,9,18),b6:sumHoles(h=>stableford(c,p,h)||0,12,18),b3:sumHoles(h=>stableford(c,p,h)||0,15,18),h18:stableford(c,p,17)||0})).sort((a,b)=>b.pts-a.pts||b.b9-a.b9||b.b6-a.b6||b.b3-a.b3||b.h18-a.h18||PLAYER_ORDER.indexOf(a.p)-PLAYER_ORDER.indexOf(b.p))}
function skins(){let total=Object.fromEntries(PLAYER_ORDER.map(p=>[p,0])),carry=0,holes=[];for(let h=0;h<18;h++){if(!completedHole('trump',h)){holes.push({winner:null,carry});continue}const ns=PLAYER_ORDER.map(p=>[p,net('trump',p,h,'skins')]);const low=Math.min(...ns.map(x=>x[1])),lows=ns.filter(x=>x[1]===low);if(lows.length===1){const units=carry+1;total[lows[0][0]]+=units;holes.push({winner:lows[0][0],units,carry:0});carry=0}else{carry++;holes.push({winner:null,carry})}}return{total,holes,unresolved:carry}}
function eventPointsMap(c){let m=Object.fromEntries(PLAYER_ORDER.map(p=>[p,0]));if(c==='elie'&&roundComplete(c)){const r=resolveFourball(),teams=fourballTeams();if(r.winner!=null)teams.forEach((t,i)=>t.forEach(p=>m[p]+=i===r.winner?5:2))}
 if(c==='northberwick'&&roundComplete(c)){semifinalResults().forEach(r=>{if(r&&r.winner){m[r.winner]+=5;m[r.loser]+=2}})}
 if(c==='castlestuart'&&roundComplete(c)){const r=resolveBumstead(),teams=bumsteadTeams();if(r.winner!=null)teams.forEach((t,i)=>t.forEach(p=>m[p]+=i===r.winner?5:2))}
 if(c==='brora'&&roundComplete(c)){const rows=wolfRanks(),base=[5,3,2,1];let i=0;while(i<rows.length){let j=i+1;while(j<rows.length&&rows[j].pts===rows[i].pts)j++;const avg=base.slice(i,j).reduce((a,b)=>a+b,0)/(j-i);for(let k=i;k<j;k++)m[rows[k].p]+=avg;i=j}}
 if(c==='royaldornoch'&&roundComplete(c)){const fm=finalMatches();if(fm){const a=fullSinglesResult(c,...fm.champ),b=fullSinglesResult(c,...fm.consolation);if(a&&a.winner){m[a.winner]+=5;m[a.loser]+=3}if(b&&b.winner){m[b.winner]+=2;m[b.loser]+=1}}}
 if(c==='trump'&&roundComplete(c)){const rows=stablefordRows(c),pts=[7,4,2,1];rows.forEach((r,i)=>m[r.p]+=pts[i])}
 if(c!=='kingsbarns'){PLAYER_ORDER.forEach(p=>{if(grossBirdie(c,p))m[p]+=1})}return m}
function cbumStandings(include=['elie','northberwick','castlestuart','brora','royaldornoch','trump']){const rows=PLAYER_ORDER.map(p=>({p,pts:0,wins:0,birdies:0,by:{}}));const byP=Object.fromEntries(rows.map(r=>[r.p,r]));include.forEach(c=>{const e=eventPointsMap(c);PLAYER_ORDER.forEach(p=>{byP[p].pts+=e[p];byP[p].by[c]=e[p];if(grossBirdie(c,p))byP[p].birdies++});if(roundComplete(c)){let winners=[];if(c==='elie'){let r=resolveFourball();if(r.winner!=null)winners=fourballTeams()[r.winner]}else if(c==='northberwick'){winners=semifinalResults().filter(x=>x&&x.winner).map(x=>x.winner)}else if(c==='castlestuart'){let r=resolveBumstead();if(r.winner!=null)winners=bumsteadTeams()[r.winner]}else if(c==='brora'){const w=wolfRanks()[0];winners=[w.p]}else if(c==='royaldornoch'){const fm=finalMatches();if(fm){const r=fullSinglesResult(c,...fm.champ);if(r&&r.winner)winners=[r.winner]}}else if(c==='trump'){winners=[stablefordRows(c)[0].p]}winners.forEach(p=>byP[p].wins++)}});const trumpRank=roundComplete('trump')?Object.fromEntries(stablefordRows('trump').map((r,i)=>[r.p,i])):Object.fromEntries(PLAYER_ORDER.map(p=>[p,0]));rows.sort((a,b)=>b.pts-a.pts||b.wins-a.wins||(trumpRank[a.p]??0)-(trumpRank[b.p]??0)||b.birdies-a.birdies||PLAYER_ORDER.indexOf(a.p)-PLAYER_ORDER.indexOf(b.p));return rows}
function playerLabel(p){return state.players[p].name}
function scoreSummary(c){const e=COURSE_DATA[c].event;if(e==='qualifier'||e==='finale'){const r=stablefordRows(c);return`${playerLabel(r[0].p)} ${r[0].pts} pts`}if(e==='fourball')return resolveFourball().display;if(e==='semis')return semifinalResults().map(r=>r?matchStateText(r.full):'').join(' • ');if(e==='bumstead')return resolveBumstead().display;if(e==='wolf'){let w=wolfRanks();return`${playerLabel(w[0].p)} ${w[0].pts} Wolf pts`}if(e==='finals'){const fm=finalMatches();if(!fm)return'Awaiting semifinals';return[fullSinglesResult(c,...fm.champ),fullSinglesResult(c,...fm.consolation)].map(r=>r?matchStateText(r.full):'').join(' • ')}return''}
function progress(c){let done=0;for(let h=0;h<18;h++)if(holeReady(c,h))done++;return done}
function render(){document.querySelectorAll('.navbtn').forEach(b=>b.classList.toggle('active',b.dataset.tab===state.ui.tab));const app=document.getElementById('app');if(state.ui.tab==='rounds')app.innerHTML=state.ui.round?renderRound(state.ui.round):renderRounds();else if(state.ui.tab==='standings')app.innerHTML=renderStandings();else if(state.ui.tab==='bracket')app.innerHTML=renderBracket();else app.innerHTML=renderSettings();bind()}
const TRIP_DATES={kingsbarns:'2026-09-05',elie:'2026-09-06',northberwick:'2026-09-07',castlestuart:'2026-09-09',brora:'2026-09-10',royaldornoch:'2026-09-11',trump:'2026-09-12'};
function localISODate(){const d=new Date(),y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${day}`}
function todayCourse(){const d=localISODate();return Object.keys(TRIP_DATES).find(c=>TRIP_DATES[c]===d)||null}
function suggestedRound(){const inProgress=Object.keys(COURSE_DATA).find(c=>progress(c)>0&&progress(c)<18);return inProgress||todayCourse()||null}
function isStandalone(){return !!(navigator.standalone||window.matchMedia?.('(display-mode: standalone)').matches)}